### ISSUE TITLE
still showing ads

### ISSUE THREAD

**Issue by mrikumar89** [SEVENNetworks/AdClear#20]
Youtube ads are not blocked...whenever i play video in youtube app it shows ads.it is very annoying. Plzz fix it.

**Comment by OSMCanada** [comment]
I noticed this too but then I realized I forgot to enable Advanced Protection; once I enabled Advanced Protection AdClear blocked the YouTube adverts successfully.

Specs:
ZTE K85 Tablet (non-rooted)
Android 5.0.2
AdClear 5.50.1544.0

**Comment by SEVENNetworks** [comment]
Yes, you have to make sure to turn on Advanced Protection to block YouTube ads because they use SSL and even double encryption now.  We are aware that we don't block all the ads on YouTube and are working to block all of them.

We recommend our users clear their data for the YouTube app to improve AdClear's ad blocking abilities.  Here is a link to follow, which explains the steps needed to get the best possible results: https://www.seven.com/adclear-faq.php#youtube_ads.
