### ISSUE TITLE
My additional lists are disabled after every upgrade

### ISSUE THREAD

**Issue by raqua** [SEVENNetworks/AdClear#28]
Every time I upgrade, additional lists that I enabled are disabled again. It would be nice to store the settings. Thanks.

**Comment by SEVENNetworks** [comment]
Hello Raqua,

Thank you for your feedback.  We are sorry if the upgrade inconvenienced you in any way.  

Currently, we don't store any of your settings on our end because of privacy concerns, but do store your settings locally on your device.  So unless you are clearing your data for AdClear, then your settings should remain in tact.  However, if you are not clearing your data, please let us know.  We will need to look further into this issue.

Thank you for your time and for using AdClear!

Chastity Rhodes
Data Specialist
SEVEN Networks, LLC

**Comment by raqua** [comment]
I have two phones, where I use your app. 
One is running Android 4.4 and I had to reenable all the additional lists.
The other one is running Android 6.0.1 and my settings were kept on latest upgrade.

**Comment by raqua** [comment]
Why is this issue closed ?
