### ISSUE TITLE
Looses internet connection

### ISSUE THREAD

**Issue by monjanse** [SEVENNetworks/AdClear#34]
When i activating ad remove basic and advanced protection, youtube looses internet connection and the internet connection in internet app goes on and off.
![screenshot_2016-10-02-22-22-14](https://cloud.githubusercontent.com/assets/19509482/19023719/7955796a-88f5-11e6-8fd7-9aaeb7f20ab1.png)

**Comment by csandlin1** [comment]
Hey there. Thanks for sending this in. Try shutting down the YouTube app process, reboot the phone, clear YouTube's Cache (in App Manager), then turn AdClear on. If that doesn't help, let me know.

**Comment by SophiaGlazova** [comment]
Hello, 
We are currently working on this issue. Could you please try our upcoming beta release? This issue should be fixed in upcoming beta.

**Comment by SEVENNetworks** [comment]
This user is in beta and is on the Pre-CCI, has been on CCI, and is on CCI archive.

**Comment by SEVENNetworks** [comment]
These directions are wrong Christian. Also, this user is a beta user, on CCI, on Pre-CCI, and in CCI archive. We know about her issues and are working on them already.

**Comment by SEVENNetworks** [comment]
Hello Monica,

Thank you for feedback.  We have been working on this issue for you and as soon as we have more to share on it, you will be the first to know.  Please let us know if there is anything else we can help you with.

Thanks for using AdClear!

**Comment by monjanse** [comment]
Ok. Youtube video ads are ceep coming back after some time without wifi avaivable (only 4g, forexample in the town outside my wifi network) so i have to clear cacle very often on youtube on android 6.01 on note 4 910f.

**Comment by SEVENNetworks** [comment]
Hello Monica,

Thank you for replying.  That is very interesting to know and we are in fact testing a very similar theory right now.  We have reason to believe that during the time a user switches from WiFi to mobile data, and even back to WiFi, that YouTube inserts ads into the cache.  Since this happens all very quickly, you can imagine why it is difficult for us to catch the ads.  As soon as we have conclusive evidence we will be sharing it with everyone.

We appreciate all your patience with us while we finish our investigations.  Please let us know if there is anything else we can help you with.

Thank you for helping to improve AdClear!
