### ISSUE TITLE
App whitelist option

### ISSUE THREAD

**Issue by jerryn70** [SEVENNetworks/AdClear#47]
Plz create whitelist option in next version. I don't want to filter financials apps.

**Comment by SEVENNetworks** [comment]
We have a whitelist feature that will be available in our new UI version due to be released soon.  Also, AdClear shouldn't be filtering any financial apps.  We have bypassed all the major ones and any more that are reported.  Just let us know which ones and we will add them to the bypass list.  You are able to whitelist apps in App Management for the time being.  When you disable Protection for any app in App Management it will not filter that app any further unless enabled again.  Please let us know if there is anything else we can help you with.

**Comment by jerryn70** [comment]
@SEVENNetworks do you guys bypassed financial apps of other countries ? regional level financial apps?
App management option is for those who enable advance protection. There is no option for users who do not use advance protection.

Please not that you guys are very slow in responding to customers enquiry . In xda forum we can clearly see that.

**Comment by csandlin1** [comment]
If you let us know which ones, we can make sure for you. Financial institutions almost exclusively use HTTPS. If you aren't using Advanced Protection, then AdClear is already bypassing those apps by function.
