### ISSUE TITLE
[Instagram] Not blocking sponsored ads

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#95]
![Screenshot_2019-11-23-20-57-43](https://user-images.githubusercontent.com/18757054/69484528-74452c00-0e34-11ea-8244-2a393e4faeed.png)
![Screenshot_2019-11-23-21-02-32](https://user-images.githubusercontent.com/18757054/69484546-a0f94380-0e34-11ea-8731-11b12e21372c.png)

**Comment by DustinMorgan** [comment]
Instagram and all of the facebook related apps are a problem due to SSL pinning. If we try to block HTTPS ads in these apps all connections get broken and the app becomes unusable. We are working on something that will hopefully work around this without requiring root. 

In the meantime, there is not much we can do at this stage.

**Comment by GKid94** [comment]
Ok thx, just continue to work on it
